version: '3'

services:
  bot:
    build:
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/app
    tty: true
    stdin_open: true
    networks:
      - missing-pets_my-shared-network

networks:
  missing-pets_my-shared-network:
    external: true